source 'https://rubygems.org'

gem 'byebug'
gem 'hashie'
gem 'nokogiri'
gem 'capybara'
gem 'cucumber'
gem 'rubocop'
gem 'require_all'
gem 'rspec-expectations'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'typhoeus'
gem 'xpath'
